---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgDEi2cp3Eu/Fb9wvtneAncqtPy2+cSy9f7oV2GAw1CdI7g2GdUqm/88gRABJMCDa1EcAA5gbiAlqoxv6Trn1Aoy8vuM/IdbYz3ynsiP/4AhtYNr46fk82OyrhfhjJGuqj7HcGGmCUCcos8gNlT44T+uI2Y2J7Jmx7MoEi091ePeN3bACsnW0dRN8bFi8Oy79HEcWJbiQDybt9EFZTu81Hko/hS4F6bVIdTxS/Zm3oo/5EzwfYC+uYRlLV04BfVcisBlpLM35K+HaLnjYGWPbMALRUPucoRZvA6bns/UldvKSxhZOYJt9oSu+dA0nS5J/55XjbhJlv4JmvNV+/9ZmTqXsJXSRv3INiB10XAfWdeOj23zewwvfhQ74Se91JMEGi4ZeeKqo5pI4crWmJGNWbPCBcmgygerCuVyFRqhKQ/0OCUKw2AdTudjyo0+/LpTB4/saPBxRq+79eMSuTpqV4o+uhImOhrUyuNNHFBLiA4s66eWfea9oW+Z56Za7cvs6sLWDCaGJJj3gzC9jtHxb/C0Y6BbfuFBaT/kfRmBZDtmeqRKaXPJ3VMSzzsaz8g1qOxDylwqLgAVEtjv+zwqg9PegVjVLRIRBW8pwO1UspIbK65Q3AD4MOEidEUhoU7/BHAjczsljEcMgJlUT4uzbdYD3kS3GD9K8nm/H54Bgwambp3YKO+BTtEQxCcd78uEj/V5/iuYskD0ZLIbXrmu6AiionVtyD3DZw==
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
